In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ulrikthygepedersen/airbnb-listings")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/ulrikthygepedersen/airbnb-listings/1.archive...

100%|██████████| 25.5M/25.5M [00:01<00:00, 18.2MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/ulrikthygepedersen/airbnb-listings/versions/1

In [51]:
import os
df = None
try:
  df = pd.read_csv(os.path.join(path, 'Listings.csv'), encoding='latin1')
except Exception as e:
  print(e)

df.sample(19)

/tmp/ipykernel_1304/910000955.py:4: DtypeWarning: Columns (5,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, 'Listings.csv'), encoding='latin1')

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
169364,46054023,Downtown apartment in the Mexico City 404CP,37192602,2015-07-01,"Mexico City, Federal District, Mexico",within an hour,1.00,1.00,t,10.0,...,1,99,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t
101525,41846463,Recamara muy agusto,256651290,2019-04-18,"Mexico City, Mexico City, Mexico",NaN,NaN,NaN,f,1.0,...,2,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t
115585,34234982,NYC Manhattan Private Room,258247777,2019-04-26,US,within an hour,1.00,0.91,f,7.0,...,3,1125,82.0,8.0,9.0,9.0,9.0,8.0,8.0,f
222616,45537324,202257 - Appartement 4 personnes Montorgueil,2667370,2012-06-18,"Paris, Ile-de-France, France",within a day,0.82,0.93,f,241.0,...,1,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t
133080,45950296,Barberini-Camera Matrimoniale,230950667,2018-12-16,"Rome, Lazio, Italy",within an hour,0.97,0.99,f,27.0,...,1,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t
73273,21423292,Sunny terrace apartment,130445565,2017-05-15,"Mexico City, Mexico City, Mexico",within an hour,1.00,1.00,t,2.0,...,2,1125,98.0,10.0,10.0,10.0,10.0,10.0,10.0,f
214261,11131988,Gaze at the Atlantic Ocean from a Glamorous Cl...,57849948,2016-02-08,"Cape Town, Western Cape, South Africa",within a few hours,1.00,1.00,f,1.0,...,10,30,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
242065,36993964,Charmant studio au coeur de Paris avec plantes,89082820,2016-08-10,"Paris, Ile-de-France, France",within an hour,1.00,0.80,f,0.0,...,5,25,95.0,10.0,9.0,10.0,10.0,10.0,10.0,f
148064,8913768,Economy Room,46615976,2015-10-15,"Istanbul, Istanbul, Turkey",NaN,NaN,NaN,f,4.0,...,1,1125,80.0,8.0,8.0,10.0,10.0,10.0,10.0,t
201511,42549177,Tranquil sunny cottage in beautiful Constantia,135087219,2017-06-14,"Cape Town, Western Cape, South Africa",within an hour,1.00,1.00,f,0.0,...,2,21,97.0,10.0,10.0,10.0,10.0,9.0,10.0,f
226567,21580673,Gorgeous Apartment in the Haut-Marais!,147018685,2017-08-21,"Paris, Ile-de-France, France",within an hour,0.84,0.90,f,78.0,...,1,1000,90.0,10.0,10.0,10.0,10.0,10.0,9.0,f
141794,46581691,Private Room In Luxury&Decent Neighborhood,150409344,2017-09-13,TR,within an hour,1.00,1.00,f,0.0,...,1,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f
116588,45743640,Amplia habitacion en departamento compartido.,257791787,2019-04-24,"Mexico City, Mexico City, Mexico",within a few hours,1.00,1.00,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t
252089,13694427,Studio chaleureux dans le Marais,79820105,2016-06-25,FR,NaN,NaN,NaN,f,1.0,...,5,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f
255785,34055821,Lovely apart in Batignolles,66027219,2016-04-06,"Bordeaux, France",NaN,NaN,NaN,f,1.0,...,1,14,100.0,8.0,8.0,6.0,8.0,10.0,8.0,f
45532,38512370,Ã¦âºÂ¼Ã¨Â°Â·Ã¥Â¸âÃ¤Â¸Â­Ã¥Â¿ÆÃ¤Â¸Â¤Ã¥Â®Â¤Ã¤...,67585919,2016-04-17,"Ratchathewi, Bangkok, Thailand",within an hour,0.93,0.96,f,48.0,...,1,1125,91.0,9.0,9.0,9.0,9.0,10.0,9.0,t
119346,32528831,Private Rooftop Exposed Brick Apartment,244438661,2019-02-20,"San Francisco, California, United States",NaN,NaN,1.00,f,2.0,...,30,1125,100.0,10.0,9.0,10.0,10.0,10.0,10.0,t
67325,20064776,Small cozy apartment in San Giovanni,23446740,2014-11-07,"Rome, Lazio, Italy",within an hour,1.00,0.93,f,12.0,...,3,1125,87.0,9.0,8.0,10.0,10.0,9.0,9.0,f
133489,35925451,KAYA MADRID STANDART ROOM,45788344,2015-10-05,"Fethiye, MuÃÅ¸la, Turkey",within a few hours,0.94,0.57,f,1005.0,...,1,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279537 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  object
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: float64(13), int64(6), object(14)
memory usage: 70.4+ MB

In [5]:
df.isna().sum()

listing_id                          0
name                              175
host_id                             0
host_since                        165
host_location                     840
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                 165
host_total_listings_count         165
host_has_profile_pic              165
host_identity_verified            165
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                        29435
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating            91405
review_scores_accuracy          91713
review_scores_cleanliness       91665
review_scores_checkin           91771
review_scores_communication     91687
review_scores_location          91775
review_scores_value             91785
instant_bookable                    0
dtype: int64

# Data Preprocessing

In [52]:
df = df.drop(columns=[
    'listing_id',
    'name',
    'district',
    'host_response_time',
    'host_response_rate',
    'host_acceptance_rate'
])
df.sample(5)

,host_id,host_since,host_location,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,city,latitude,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
117445,150854912,2017-09-16,"Rio de Janeiro, State of Rio de Janeiro, Brazil",t,4.0,t,t,Recreio dos Bandeirantes,Rio de Janeiro,-23.02727,...,4,1125,98.0,10.0,10.0,10.0,10.0,10.0,9.0,f
61388,222724867,2018-10-26,"Istanbul, Istanbul, Turkey",f,13.0,t,t,Esenyurt,Istanbul,41.01473,...,1,1125,90.0,10.0,6.0,10.0,9.0,10.0,10.0,f
64961,247690688,2019-03-08,"Tamarama, New South Wales, Australia",f,2.0,t,t,Waverley,Sydney,-33.88594,...,2,1125,100.0,10.0,9.0,10.0,10.0,10.0,9.0,f
147980,24681732,2014-12-10,"Sydney, New South Wales, Australia",f,2.0,t,f,Ku-Ring-Gai,Sydney,-33.74130,...,1,1125,86.0,9.0,8.0,10.0,9.0,9.0,9.0,f
90604,23997712,2014-11-21,"Mexico City, Mexico City, Mexico",f,1.0,t,f,La Magdalena Contreras,Mexico City,19.31972,...,365,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t

In [53]:
# Replacing Numerical NaN
df['bedrooms'].fillna(df['bedrooms'].median(), inplace=True)

review_cols = [
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value',
    'host_total_listings_count'
]

df[review_cols] = df[review_cols].fillna(0)

/tmp/ipykernel_1304/2242238587.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bedrooms'].fillna(df['bedrooms'].median(), inplace=True)

In [54]:
# Replacing NaN categorical data
cat_cols = [
    'host_since',
    'host_location',
    'host_is_superhost',
    'host_has_profile_pic',
    'host_identity_verified'
]

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_1304/2831912873.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [25]:
df.isna().sum()

listing_id                          0
name                              175
host_id                             0
host_since                          0
host_location                       0
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                   0
host_total_listings_count           0
host_has_profile_pic                0
host_identity_verified              0
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                            0
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating                0
review_scores_accuracy              0
review_scores_cleanliness           0
review_scores_checkin               0
review_scores_communication         0
review_scores_location              0
review_scores_value                 0
instant_bookable                    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   host_id                      279712 non-null  int64
 1   host_since                   279712 non-null  object
 2   host_location                279712 non-null  object
 3   host_is_superhost            279712 non-null  object
 4   host_total_listings_count    279712 non-null  float64
 5   host_has_profile_pic         279712 non-null  object
 6   host_identity_verified       279712 non-null  object
 7   neighbourhood                279712 non-null  object
 8   city                         279712 non-null  object
 9   latitude                     279712 non-null  float64
 10  longitude                    279712 non-null  float64
 11  property_type                279712 non-null  object
 12  room_type                    279712 non-null  object
 13  accommodates                 279712 non-null  int64
 14  bedrooms                     279712 non-null  float64
 15  amenities                    279712 non-null  object
 16  price                        279712 non-null  int64
 17  minimum_nights               279712 non-null  int64
 18  maximum_nights               279712 non-null  int64
 19  review_scores_rating         279712 non-null  float64
 20  review_scores_accuracy       279712 non-null  float64
 21  review_scores_cleanliness    279712 non-null  float64
 22  review_scores_checkin        279712 non-null  float64
 23  review_scores_communication  279712 non-null  float64
 24  review_scores_location       279712 non-null  float64
 25  review_scores_value          279712 non-null  float64
 26  instant_bookable             279712 non-null  object
dtypes: float64(11), int64(5), object(11)
memory usage: 57.6+ MB

In [11]:
obj_df = df.select_dtypes(include='object')
obj_df.sample(25)

,host_since,host_location,host_is_superhost,host_has_profile_pic,host_identity_verified,neighbourhood,city,property_type,room_type,amenities,instant_bookable
31713,2013-04-30,"Paris, Ile-de-France, France",f,t,t,Batignolles-Monceau,Paris,Entire apartment,Entire place,"[""Paid parking off premises"", ""Heating"", ""TV"",...",f
239513,2012-11-02,"Los Angeles, California, United States",f,t,t,Upper West Side,New York,Entire apartment,Entire place,"[""Oven"", ""Smoke alarm"", ""Essentials"", ""Dishes ...",f
165383,2018-10-11,"Newtown, New South Wales, Australia",f,t,t,Marrickville,Sydney,Private room in house,Private room,"[""Washer"", ""Iron"", ""Long term stays allowed"", ...",t
94972,2017-08-31,"Paris, Ile-de-France, France",f,t,t,Louvre,Paris,Private room in apartment,Private room,"[""Shampoo"", ""Heating"", ""TV"", ""Iron"", ""Kitchen""...",t
236046,2018-07-24,US,f,t,f,Midtown,New York,Entire apartment,Entire place,"[""Hair dryer"", ""Stove"", ""Smoke alarm"", ""Hanger...",f
120161,2017-01-02,"New York, New York, United States",t,t,t,Flushing,New York,Private room in apartment,Private room,"[""Refrigerator"", ""Microwave"", ""Shampoo"", ""Air ...",t
124305,2012-11-19,"Rio de Janeiro, Rio de Janeiro, Brazil",f,t,t,Botafogo,Rio de Janeiro,Private room in apartment,Private room,"[""Kitchen"", ""Washer"", ""Air conditioning"", ""Lon...",f
219209,2016-10-20,"Alexandria, Virginia, United States",f,t,t,Basaksehir,Istanbul,Entire apartment,Entire place,"[""Iron"", ""Essentials"", ""Heating"", ""Air conditi...",f
241989,2017-01-04,"Paris, Ile-de-France, France",f,t,t,Palais-Bourbon,Paris,Entire apartment,Entire place,"[""Dishwasher"", ""Essentials"", ""Stove"", ""Hot wat...",f
93241,2018-05-20,TH,f,t,f,Bang Rak,Bangkok,Private room in hostel,Private room,"[""Air conditioning"", ""Lock on bedroom door"", ""...",f
207113,2019-11-11,"Cape Town, Western Cape, South Africa",f,t,t,Ward 115,Cape Town,Entire serviced apartment,Entire place,"[""Air conditioning"", ""Long term stays allowed""...",t
119082,2013-04-15,"Paris, Ile-de-France, France",f,t,t,Opera,Paris,Private room in apartment,Private room,"[""Extra pillows and blankets"", ""Dishes and sil...",t
189284,2012-08-11,"New York, New York, United States",t,t,t,Bedford-Stuyvesant,New York,Private room in apartment,Private room,"[""Private living room"", ""Smoke alarm"", ""Hanger...",f
236368,2016-07-14,"New York, New York, United States",f,t,t,Upper East Side,New York,Entire apartment,Entire place,"[""Refrigerator"", ""Microwave"", ""Air conditionin...",f
16526,2014-07-17,"New York, New York, United States",f,t,t,East Village,New York,Entire apartment,Entire place,"[""Refrigerator"", ""Single level home"", ""Microwa...",f
134767,2019-02-21,BR,f,t,t,Botafogo,Rio de Janeiro,Private room in apartment,Private room,"[""Elevator"", ""Kitchen"", ""Washer"", ""Air conditi...",f
81251,2013-02-07,"Sydney, New South Wales, Australia",f,t,t,Pittwater,Sydney,Entire house,Entire place,"[""HDTV with Netflix"", ""Bed linens"", ""Coffee ma...",f
247941,2016-02-03,"Istanbul, Turkey",f,t,t,Kartal,Istanbul,Entire apartment,Entire place,"[""Iron"", ""Essentials"", ""Bed linens"", ""Heating""...",t
191227,2020-03-24,BR,f,t,f,Catete,Rio de Janeiro,Private room in apartment,Private room,"[""Elevator"", ""Dedicated workspace"", ""Kitchen"",...",f
162920,2019-11-22,"Bangkok, Bangkok, Thailand",f,t,t,Huai Khwang,Bangkok,Entire condominium,Entire place,"[""Air conditioning"", ""Pool"", ""Elevator"", ""Free...",f
6153,2014-07-07,"Paris, Ile-de-France, France",f,t,f,Menilmontant,Paris,Entire apartment,Entire place,"[""Heating"", ""Elevator"", ""Wifi"", ""Smoke alarm"",...",f
72744,2014-10-02,"Cape Town, Western Cape, South Africa",f,t,t,Ward 23,Cape Town,Entire apartment,Entire place,"[""Beachfront"", ""Long term stays allowed"", ""Fir...",t
49459,2015-06-07,"Paris, Ile-de-France, France",f,t,f,Batignolles-Monceau,Paris,Entire apartment,Entire place,"[""Shampoo"", ""Garden or backyard"", ""Heating"", ""...",f
206590,2015-04-16,"Cape Town, Western Cape, South Africa",f,t,t,Ward 113,Cape Town,Entire guest suite,Entire place,"[""Hair dryer"", ""Long term stays allowed"", ""Iro...",f
226335,2015-07-30,"Paris, Ile-de-France, France",f,t,t,Luxembourg,Paris,Entire apartment,Entire place,"[""Essentials"", ""Stove"", ""Hot water"", ""Hangers""...",f

In [55]:
df.drop(columns=['amenities'], inplace=True)

In [56]:
df.drop(columns=['host_id'], inplace= True)
df.sample(20)

,host_since,host_location,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,city,latitude,longitude,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
25591,2014-05-23,"New York, New York, United States",f,1.0,t,t,Williamsburg,New York,40.70771,-73.95218,...,30,1125,98.0,10.0,10.0,10.0,10.0,10.0,9.0,f
197694,2019-06-16,"Manawatu-Wanganui, New Zealand",f,1.0,t,t,Suanluang,Bangkok,13.74345,100.60137,...,1,365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t
206288,2019-07-23,"Cape Town, Western Cape, South Africa",f,0.0,t,f,Ward 84,Cape Town,-34.09002,18.84845,...,10,18,80.0,10.0,6.0,10.0,10.0,10.0,10.0,f
159369,2014-07-11,"Bondi Beach, New South Wales, Australia",f,1.0,t,f,Waverley,Sydney,-33.89042,151.26703,...,1,30,90.0,10.0,10.0,10.0,10.0,10.0,10.0,f
91856,2019-10-13,FR,f,0.0,t,f,Observatoire,Paris,48.83559,2.32478,...,1,1125,90.0,9.0,8.0,9.0,9.0,10.0,9.0,t
269257,2015-04-01,"Paris, Ile-de-France, France",f,1.0,t,t,Observatoire,Paris,48.83389,2.32478,...,3,15,100.0,10.0,10.0,10.0,10.0,10.0,9.0,f
225776,2013-12-15,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,4.0,t,t,Copacabana,Rio de Janeiro,-22.98248,-43.19223,...,1,365,94.0,10.0,10.0,10.0,9.0,10.0,10.0,f
59114,2019-09-02,FR,f,0.0,t,t,Buttes-Montmartre,Paris,48.89178,2.33954,...,3,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t
176850,2017-10-27,China,f,4.0,t,t,Randwick,Sydney,-33.92121,151.22611,...,7,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
196684,2019-04-16,"BeÃ Å¸iktaÃ Å¸, Istanbul, Turkey",f,1.0,t,f,Besiktas,Istanbul,41.04527,29.00082,...,3,30,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
208499,2021-01-04,NL,f,0.0,t,f,Ward 23,Cape Town,-33.81094,18.47736,...,5,180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
92490,2019-02-01,"Paris, Ile-de-France, France",t,8.0,t,t,Bourse,Paris,48.86960,2.34378,...,1,1125,99.0,10.0,10.0,10.0,10.0,10.0,9.0,t
112715,2015-07-30,"New York, New York, United States",f,1.0,t,t,Maspeth,New York,40.73329,-73.89463,...,30,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
8171,2014-06-22,"Paris, Ile-de-France, France",f,1.0,t,t,Observatoire,Paris,48.82658,2.32872,...,6,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
232471,2013-07-15,"Paris, Ile-de-France, France",f,2.0,t,t,Buttes-Chaumont,Paris,48.88312,2.37668,...,5,8,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
121341,2020-01-05,TR,f,0.0,t,f,Besiktas,Istanbul,41.04390,29.00561,...,3,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t
17717,2014-05-31,"Sydney, New South Wales, Australia",f,1.0,t,t,Marrickville,Sydney,-33.89189,151.17934,...,2,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t
6830,2015-10-13,"Paris, Ile-de-France, France",f,1.0,t,f,Hotel-de-Ville,Paris,48.85815,2.35234,...,1,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
11691,2011-11-06,"New York, New York, United States",f,1.0,t,f,Lower East Side,New York,40.71506,-73.98993,...,30,1125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,f
68995,2013-04-19,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,63.0,t,t,Copacabana,Rio de Janeiro,-22.97968,-43.19161,...,1,1125,77.0,9.0,8.0,10.0,9.0,9.0,8.0,t

In [57]:
review_cols = [
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value'
]

cum_rev = df[review_cols].sum(axis=1)
df.drop(columns=review_cols, inplace=True)
df['review_scores_rating'] = cum_rev/ len(review_cols)
df.sample(20)

,host_since,host_location,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,price,minimum_nights,maximum_nights,instant_bookable,review_scores_rating
147411,2018-02-26,"Paris, Ile-de-France, France",f,5.0,t,f,Luxembourg,Paris,48.85326,2.34256,Room in boutique hotel,Private room,1,1.0,80,1,1125,t,19.428571
48327,2017-04-14,"Paris, Ile-de-France, France",f,178.0,t,t,Buttes-Montmartre,Paris,48.88249,2.34064,Entire apartment,Entire place,2,1.0,100,1,1125,t,0.000000
14187,2013-07-28,Italia,f,1.0,t,f,II Parioli/Nomentano,Rome,41.93657,12.51699,Entire apartment,Entire place,6,3.0,70,2,1125,f,22.142857
141282,2016-07-12,ZA,t,2.0,t,f,Ward 58,Cape Town,-33.96608,18.48000,Entire guest suite,Entire place,2,1.0,1000,1,1125,f,22.285714
171239,2020-01-22,MX,f,0.0,t,f,Iztacalco,Mexico City,19.40231,-99.07830,Private room in guesthouse,Private room,2,1.0,285,10,15,t,0.000000
248572,2018-08-11,"Mexico City, Mexico City, Mexico",t,15.0,t,t,Cuauhtemoc,Mexico City,19.41546,-99.17878,Entire apartment,Entire place,2,1.0,1089,2,28,t,22.571429
270740,2018-06-04,"Paris, Ile-de-France, France",t,1.0,t,t,Buttes-Montmartre,Paris,48.89245,2.33387,Entire apartment,Entire place,2,1.0,140,2,15,f,22.428571
269067,2015-09-24,"Paris, Ile-de-France, France",f,1.0,t,t,Enclos-St-Laurent,Paris,48.87923,2.36607,Entire apartment,Entire place,2,1.0,100,1,1124,f,21.857143
44790,2012-07-20,"Istanbul, Turkey",f,22.0,t,t,Fatih,Istanbul,41.00211,28.97675,Entire apartment,Entire place,4,1.0,177,1,1125,t,20.285714
213253,2015-09-09,"Cape Town, Western Cape, South Africa",f,1.0,t,t,Ward 61,Cape Town,-34.21297,18.45959,Entire cottage,Entire place,4,2.0,1400,3,30,f,22.857143
79343,2017-06-26,"London, England, United Kingdom",f,184.0,t,t,Batignolles-Monceau,Paris,48.88835,2.32154,Entire condominium,Entire place,4,2.0,352,4,1125,f,0.000000
189060,2020-03-03,"Flamengo, State of Rio de Janeiro, Brazil",f,0.0,t,t,Flamengo,Rio de Janeiro,-22.93417,-43.17666,Private room in apartment,Private room,1,1.0,100,7,30,f,0.000000
254989,2013-04-04,"Sydney, New South Wales, Australia",f,1.0,t,t,Sydney,Sydney,-33.88009,151.21337,Entire apartment,Entire place,3,1.0,246,5,14,f,22.000000
232469,2015-10-27,"Paris, Ile-de-France, France",f,2.0,t,t,Menilmontant,Paris,48.85110,2.40475,Entire apartment,Entire place,2,1.0,40,2,12,f,21.142857
244470,2015-10-17,"Rome, Lazio, Italy",f,19.0,t,t,I Centro Storico,Rome,41.89213,12.47155,Entire apartment,Entire place,9,3.0,139,1,200,t,0.000000
155036,2015-04-22,"Paris, Ile-de-France, France",f,1.0,t,t,Batignolles-Monceau,Paris,48.89477,2.31498,Private room in apartment,Private room,2,1.0,45,1,1125,f,22.285714
194111,2014-07-17,"Istanbul, Turkey",f,0.0,t,t,Besiktas,Istanbul,41.06151,29.00925,Private room in apartment,Private room,2,1.0,179,2,30,t,0.000000
98358,2017-03-22,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,0.0,t,t,Cidade de Deus,Rio de Janeiro,-22.95078,-43.35997,Entire house,Entire place,6,2.0,141,1,1125,t,0.000000
172723,2012-07-09,"New York, New York, United States",f,1.0,t,t,Carroll Gardens,New York,40.67859,-73.99444,Entire condominium,Entire place,2,1.0,150,30,365,f,22.285714
101202,2019-12-07,"Bangkok, Bangkok, Thailand",f,0.0,t,f,Suanluang,Bangkok,13.74179,100.60099,Entire condominium,Entire place,2,1.0,1800,2,1125,t,0.000000

In [58]:
df['host_since'] = pd.to_datetime(df['host_since'])

df['host_experience_days'] = (pd.Timestamp.today() - df['host_since']).dt.days
df.drop(columns=['host_since'], inplace=True)
df.sample(20)

,host_location,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,price,minimum_nights,maximum_nights,instant_bookable,review_scores_rating,host_experience_days
59164,FR,f,0.0,t,t,Vaugirard,Paris,48.84237,2.28684,Entire apartment,Entire place,4,2.0,85,2,1125,f,21.285714,2399
45557,"Sydney, New South Wales, Australia",f,13.0,t,t,Sydney,Sydney,-33.86390,151.20241,Entire apartment,Entire place,6,2.0,516,1,1125,t,22.000000,3064
250793,BR,f,1.0,t,f,Copacabana,Rio de Janeiro,-22.97445,-43.19281,Entire apartment,Entire place,6,3.0,900,4,15,f,0.000000,4464
153814,JP,f,1.0,t,f,Phra Nakhon,Bangkok,13.76093,100.49592,Private room in house,Private room,2,1.0,2278,1,1125,t,0.000000,2761
200266,"Sydney, New South Wales, Australia",f,1.0,t,t,Sydney,Sydney,-33.86904,151.20369,Private room in apartment,Private room,2,1.0,80,4,22,f,0.000000,4108
51180,AU,f,13.0,t,t,Marrickville,Sydney,-33.88842,151.17011,Entire apartment,Entire place,2,1.0,70,3,1125,t,0.000000,2232
131401,"Rome, Lazio, Italy",f,9.0,t,t,I Centro Storico,Rome,41.90699,12.49874,Private room in apartment,Private room,2,1.0,40,1,1125,t,19.142857,5041
212288,"Cape Town, Western Cape, South Africa",f,1.0,t,f,Ward 74,Cape Town,-34.03964,18.34842,Entire house,Entire place,8,4.0,4500,10,17,f,22.857143,3902
227937,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,2.0,t,t,Santa Teresa,Rio de Janeiro,-22.91860,-43.18784,Entire apartment,Entire place,5,2.0,200,5,7,f,0.000000,2563
131178,"Rome, Lazio, Italy",f,1.0,t,t,III Monte Sacro,Rome,41.94902,12.52459,Private room in apartment,Private room,2,1.0,34,1,1125,f,22.000000,4265
19649,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,1.0,t,f,Jacarepagua,Rio de Janeiro,-22.96596,-43.41173,Entire apartment,Entire place,4,2.0,1000,3,1125,f,0.000000,3625
224933,"Rio de Janeiro, State of Rio de Janeiro, Brazil",f,12.0,t,t,Barra da Tijuca,Rio de Janeiro,-23.00916,-43.34533,Entire apartment,Entire place,3,1.0,350,2,27,f,21.142857,3497
63986,"Rome, Lazio, Italy",f,8.0,t,t,V Prenestino/Centocelle,Rome,41.88434,12.56688,Entire apartment,Entire place,4,2.0,50,3,1125,t,0.000000,4387
153338,"Istanbul, Istanbul, Turkey",f,1.0,t,f,Uskudar,Istanbul,41.05877,29.08252,Private room in house,Private room,1,1.0,70,1,1125,t,0.000000,2356
249380,"Paris, Ile-de-France, France",f,0.0,t,t,Hotel-de-Ville,Paris,48.85299,2.35038,Entire apartment,Entire place,2,1.0,37,30,365,f,22.857143,1999
136295,"Bella Vista, New South Wales, Australia",t,1.0,t,t,The Hills Shire,Sydney,-33.72522,150.94479,Entire townhouse,Entire place,2,1.0,89,1,1125,f,22.285714,2462
2575,"Paris, Ile-de-France, France",f,1.0,t,f,Reuilly,Paris,48.83376,2.40207,Entire apartment,Entire place,2,1.0,49,1,1125,f,0.000000,3910
105219,"New York, New York, United States",f,177.0,t,t,Elmhurst,New York,40.74267,-73.87247,Private room in townhouse,Private room,1,1.0,23,30,1125,f,0.000000,3196
70258,"Guangzhou, Guangdong, China",f,61.0,t,t,Khlong Toei,Bangkok,13.70479,100.59362,Entire apartment,Entire place,2,1.0,492,1,1125,t,20.714286,2656
229517,"Paris, Ile-de-France, France",f,2.0,t,f,Buttes-Montmartre,Paris,48.89214,2.34429,Entire apartment,Entire place,4,2.0,107,4,30,f,22.857143,4695

In [49]:
print(df['room_type'].nunique())
print(df['property_type'].nunique())
print(df['city'].nunique())
print(df['neighbourhood'].nunique())
print(df['host_location'].nunique())

4
144
10
660
7159

In [59]:
df.drop(['neighbourhood', 'host_location'], axis=1, inplace=True)
df.sample(8)

,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,price,minimum_nights,maximum_nights,instant_bookable,review_scores_rating,host_experience_days
83328,f,2.0,t,t,Sydney,-33.88650,151.27692,Private room in house,Private room,2,2.0,50,2,1125,f,22.857143,3337
125655,f,1.0,t,t,Paris,48.87730,2.35804,Private room in apartment,Private room,2,1.0,42,2,1125,f,22.714286,4311
185859,f,3.0,t,t,New York,40.72814,-73.99902,Private room in apartment,Private room,1,1.0,150,1,60,f,0.000000,3341
111312,f,2.0,t,f,Sydney,-34.05322,150.71191,Private room in house,Private room,1,1.0,54,3,1125,f,0.000000,3672
169155,t,7.0,t,t,Bangkok,13.94398,100.61284,Room in hostel,Hotel room,2,1.0,698,1,366,t,22.571429,2945
161987,f,0.0,t,f,Mexico City,19.40994,-99.16741,Private room in guesthouse,Private room,1,1.0,400,1,30,t,0.000000,2999
221241,f,0.0,t,t,New York,40.74963,-73.97825,Entire apartment,Entire place,4,2.0,899,30,120,f,22.857143,3235
35262,f,1.0,t,f,Mexico City,19.43084,-99.14871,Entire apartment,Entire place,5,2.0,1500,2,1125,t,21.000000,2838

# Data Splitting

In [60]:
from sklearn.model_selection import train_test_split

X = df.drop('instant_bookable', axis=1)
y = df['instant_bookable']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [61]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223769 entries, 107825 to 142418
Data columns (total 16 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   host_is_superhost          223769 non-null  object
 1   host_total_listings_count  223769 non-null  float64
 2   host_has_profile_pic       223769 non-null  object
 3   host_identity_verified     223769 non-null  object
 4   city                       223769 non-null  object
 5   latitude                   223769 non-null  float64
 6   longitude                  223769 non-null  float64
 7   property_type              223769 non-null  object
 8   room_type                  223769 non-null  object
 9   accommodates               223769 non-null  int64
 10  bedrooms                   223769 non-null  float64
 11  price                      223769 non-null  int64
 12  minimum_nights             223769 non-null  int64
 13  maximum_nights             223769 non-null  int64
 14  review_scores_rating       223769 non-null  float64
 15  host_experience_days       223769 non-null  int64
dtypes: float64(5), int64(5), object(6)
memory usage: 29.0+ MB

# One Hot Encoding

In [62]:
from sklearn.preprocessing import OneHotEncoder


low_card_cols = ['room_type', 'city']
prop_col = 'property_type'


top_k = 20
top_categories = X_train[prop_col].value_counts().nlargest(top_k).index


X_train[prop_col] = X_train[prop_col].where(
    X_train[prop_col].isin(top_categories), 'Other'
)

X_test[prop_col] = X_test[prop_col].where(
    X_test[prop_col].isin(top_categories), 'Other'
)


#  OneHotEncoder (low card)
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
ohe.fit(X_train[low_card_cols])

X_train_low = ohe.transform(X_train[low_card_cols])
X_test_low  = ohe.transform(X_test[low_card_cols])

X_train_low_df = pd.DataFrame(
    X_train_low,
    columns=ohe.get_feature_names_out(low_card_cols),
    index=X_train.index
)

X_test_low_df = pd.DataFrame(
    X_test_low,
    columns=ohe.get_feature_names_out(low_card_cols),
    index=X_test.index
)


# OneHotEncoder (property_type)

ohe_prop = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
ohe_prop.fit(X_train[[prop_col]])

X_train_prop = ohe_prop.transform(X_train[[prop_col]])
X_test_prop  = ohe_prop.transform(X_test[[prop_col]])

X_train_prop_df = pd.DataFrame(
    X_train_prop,
    columns=ohe_prop.get_feature_names_out([prop_col]),
    index=X_train.index
)

X_test_prop_df = pd.DataFrame(
    X_test_prop,
    columns=ohe_prop.get_feature_names_out([prop_col]),
    index=X_test.index
)


X_train = X_train.drop(columns=low_card_cols + [prop_col])
X_test  = X_test.drop(columns=low_card_cols + [prop_col])

binary_cols = [
    'host_is_superhost',
    'host_has_profile_pic',
    'host_identity_verified'
]


mapping = {'t': 1, 'f': 0}


for col in binary_cols:
    X_train[col] = X_train[col].map(mapping)

for col in binary_cols:
    X_test[col] = X_test[col].map(mapping)

X_train = pd.concat([X_train, X_train_low_df, X_train_prop_df], axis=1)
X_test  = pd.concat([X_test, X_test_low_df, X_test_prop_df], axis=1)

In [63]:
X_train.sample(10)

,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,accommodates,bedrooms,price,minimum_nights,...,property_type_Private room in condominium,property_type_Private room in guest suite,property_type_Private room in guesthouse,property_type_Private room in house,property_type_Private room in serviced apartment,property_type_Private room in townhouse,property_type_Room in aparthotel,property_type_Room in boutique hotel,property_type_Room in hotel,property_type_Shared room in apartment
145373,0,1.0,1,1,-22.79836,-43.19508,2,1.0,80,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
161886,1,7.0,1,0,13.75248,100.50220,1,1.0,490,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71603,0,0.0,1,0,48.84104,2.26527,6,1.0,84,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215755,0,1.0,1,0,-33.85678,151.05740,2,1.0,42,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
62838,0,7.0,1,1,-33.97535,18.46971,2,1.0,900,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
120675,0,3.0,1,1,40.75750,-73.93581,2,1.0,40,30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
174301,0,2.0,1,1,-23.00564,-43.34156,2,1.0,142,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92442,0,36.0,1,1,13.75107,100.52927,4,1.0,450,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127590,0,1.0,1,1,40.71694,-73.95386,2,1.0,98,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119586,1,3.0,1,1,-33.93288,151.12600,2,1.0,40,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [78]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

x_test = scaler.transform(X_test)